### PR TITLE
Added view to break relations

### PR DESCRIPTION
**Pull request by JustinWingChungHui**

### CODE REVIEW

**Comment by szech** [comment]
Do we need a confirmation dialog to break relationships?

PS Adam Lambert is now a person in the system. ;-)

**Comment by szech** [comment]
Pps: managed to test on Chrome for mobile by spamming the touch action in
the tree view. We need to fix the responsiveness....

**Comment by JustinWingChungHui** [comment]
Sorry what does that mean?

**Comment by JustinWingChungHui** [comment]
I've deleted Adam Lambert.  I don't think we need a popup for breaking relationships.  You can always create it again really easily

**Pull request merged**
